pvCast:
  name: cast-pv
  storage: 1Gi
  accessMode: ReadWriteOnce
  hostPath: /var/lib/rancher/k3s/storage/cast
  storageClassName: ""

pvMovie:
  name: movie-pv
  storage: 2Gi
  accessMode: ReadWriteOnce
  hostPath: /var/lib/rancher/k3s/storage/movie
  storageClassName: ""


pvcCast:
  name: pvc-cast
  accessMode: ReadWriteOnce
  storageClassName: ""
  volumeName: cast-pv
  storage: 128Mi

pvcMovie:
  name: pvc-movie
  accessMode: ReadWriteOnce
  storageClassName: ""
  volumeName: movie-pv
  storage: 128Mi


castService:
  name: service-castdb
  type: ClusterIP
  port: 5432



movieService:
  name: service-moviedb
  type: ClusterIP
  port: 5432


castStatefulSet:
  name: castdb
  serviceName: service-castdb
  replicas: 1
  labels:
    app: castdb
  volume:
    name: castdb
    claimName: pvc-cast
  container:
    name: castdb
    image: postgres:12.1-alpine
    port: 5432
    mountPath: "/var/lib/postgresql/data"
    env:
      POSTGRES_USER: cast_db_username
      POSTGRES_PASSWORD: cast_db_password
      POSTGRES_DB: cast_db_dev


movieStatefulSet:
  name: moviedb
  serviceName: service-moviedb
  replicas: 1
  labels:
    app: moviedb
  volume:
    name: moviedb
    claimName: pvc-cast
  container:
    name: moviedb
    image: postgres:12.1-alpine
    port: 5432
    mountPath: "/var/lib/postgresql/data"
    env:
      POSTGRES_USER: cast_db_username
      POSTGRES_PASSWORD: cast_db_password
      POSTGRES_DB: cast_db_dev



