castService:
  name: service-castdb
  type: ClusterIP
  port: 8080
  targetPort: 8080
  nodePort: 30002

castApp:
  name: nginxProxy
  app: nginxProxy
  selector:
    app: nginxProxy
  labels:
    app: nginxProxy
  container:
    name: nginxProxy
    image: fm92962/nginx-proxy:v1
